# Generated by Django 4.0.6 on 2022-07-28 13:51

import back.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='post/default.jpg', upload_to=back.models.user_directory_path)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                
            ],
        ),
    ]
