# Generated by Django 3.2.16 on 2022-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='mac',
            field=models.TextField(blank=b'I00\n'),
        ),
    ]
