# Generated by Django 4.0.6 on 2022-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_images_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
