# Generated by Django 4.0.6 on 2022-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_images_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='img_data',
            field=models.TextField(blank=True),
        ),
    ]
